root = "."
tmp_dir = "tmp" 

[build]
    cmd = "go build -o ./tmp/main.exe ./main/main.go"
    bin = "./tmp/main.exe"
    delay = 1000 #ms
    exclude_dir = ["assets", "tmp", "vendor"]
    exclude_regex = ["_test\\.go"]
    include_ext = ["go", "tmpl", "html"]