root = "."
tmp_dir = "tmp" 

[build]
    # pre_cmd = "templ generate"
    cmd = "templ generate && go build -o ./tmp/main.exe ./main/main.go"
    bin = "./tmp/main.exe"
    delay = 1000 #ms
    exclude_dir = ["assets", "tmp", "vendor"]
    exclude_regex = ["_test\\.go", ".*_templ.go"]
    include_ext = ["go", "templ", "html"]